import { expect, test } from '@playwright/test'

test('заказ сохраняется после ошибки и завершается со второй попытки', async ({ page }) => {
  await page.goto('#/')
  await page.getByRole('button', { name: /Заказать еду/ }).click()
  await expect(page.getByRole('heading', { name: /Где хотите/ })).toBeVisible()
  await page.getByRole('button', { name: /Питькофе/ }).click()
  await page.getByRole('button', { name: /Смотреть доступное меню/ }).click()
  await page.getByRole('button', { name: /Открыть Ньокки/ }).click()
  await page.getByRole('button', { name: /Добавить ·/ }).click()
  await page.getByRole('button', { name: /К оформлению/ }).click()
  await page.getByRole('textbox', { name: 'Имя' }).fill('Тест')
  await page.getByRole('textbox', { name: 'Телефон' }).fill('+70000000000')
  await page.getByRole('button', { name: 'Выбрать' }).last().click()
  await page.getByRole('dialog', { name: 'Выбор оплаты' }).getByRole('button', { name: 'Банковская карта' }).click()
  await page.getByRole('button', { name: /Подтвердить заказ/ }).click()
  await expect(page.getByRole('heading', { name: 'Корзина на месте' })).toBeVisible()
  await page.getByRole('button', { name: 'Вернуться к оплате' }).click()
  await expect(page.getByText('Банковская карта')).toBeVisible()
  await page.getByRole('button', { name: /Подтвердить заказ/ }).click()
  await expect(page.getByRole('heading', { name: 'Заказ сохранён' })).toBeVisible()
})

test('бронирование доходит до подтверждения', async ({ page }) => {
  await page.goto('#/booking')
  await page.getByRole('button', { name: /Питькофе/ }).click()
  await page.getByRole('button', { name: 'Завтра' }).click()
  await page.getByRole('button', { name: '20:00' }).click()
  await page.getByRole('button', { name: 'Увеличить' }).click()
  await page.getByRole('button', { name: /Сохранить запрос/ }).click()
  await expect(page.getByText('Номер запроса')).toBeVisible()
  await expect(page.getByRole('heading', { name: /Питькофе завтра в 20:00/i })).toBeVisible()
  await expect(page.getByText(/3 гостя/)).toBeVisible()
})

test('заказ торта формирует отдельную заявку', async ({ page }) => {
  await page.goto('#/cake')
  await page.getByRole('button', { name: 'Детский' }).click()
  await page.getByRole('button', { name: /Оникс/ }).click()
  await page.getByRole('button', { name: /Вес · изменить/ }).click()
  await page.getByRole('button', { name: /Дата · изменить/ }).click()
  await page.getByRole('button', { name: /Сохранить заявку/ }).click()
  await expect(page.getByText('Заявка', { exact: true })).toBeVisible()
  await expect(page.getByText(/Детский · «Оникс» · 3 кг/)).toBeVisible()
  await expect(page.getByText(/К \d{1,2} [а-яё]+/i)).toBeVisible()
})

test('поиск и корзина остаются в контексте MamaDonna', async ({ page }) => {
  await page.goto('#/brand/mamadonna/menu')
  await page.getByRole('button', { name: 'Поиск' }).click()
  await page.getByPlaceholder('Блюдо или категория').fill('омлет')
  await expect(page.getByText('MamaDonna · 650 ₽')).toBeVisible()
  await page.getByRole('button', { name: /Открыть Омлет/ }).click()
  await page.getByRole('button', { name: /Добавить · 650 ₽/ }).click()
  await expect(page.getByText('Омлет с креветками и авокадо')).toBeVisible()
  await expect(page.getByText('650 ₽').first()).toBeVisible()
})

test('презентация и ключевые deep links открываются напрямую', async ({ page }) => {
  await page.goto('case/')
  await expect(page.getByRole('heading', { name: /Сначала задача/ })).toBeVisible()
  const caseUrl = page.url()
  const hrefs = await page.locator('a[href*="#/"]').evaluateAll((links) => links.map((link) => link.getAttribute('href')))
  expect(hrefs.length).toBeGreaterThanOrEqual(6)
  for (const href of hrefs) {
    await page.goto(new URL(href!, caseUrl).href)
    await expect(page.locator('#root')).not.toBeEmpty()
  }
  await page.goto('case/')
  await expect(page.locator('a[href="mailto:hello@eh.works"]')).toHaveCount(1)
  await expect(page.locator('a[href="https://eh.works"]')).toHaveCount(1)
  await page.goto('#/repeat')
  await expect(page.getByRole('heading', { name: 'Нет заказа для повтора' })).toBeVisible()
})

test('пустые прямые ссылки не создают позиции и не допускают оформление', async ({ page }) => {
  await page.goto('#/checkout/esttort')
  await expect(page.getByRole('heading', { name: 'Оформлять пока нечего' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Подтвердить заказ/ })).toHaveCount(0)
  await page.goto('#/payment-error')
  await expect(page.getByRole('heading', { name: 'Оформлять пока нечего' })).toBeVisible()
  await page.goto('#/cart/pitcofe')
  await expect(page.getByRole('heading', { name: 'Корзина пока пуста' })).toBeVisible()
})
